name: build

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - master

jobs:
  build:

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
          - windows-2022
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    - name: Install mamba
      run: |
        conda install -c conda-forge mamba=0.20.0
    - name: Install dependencies
      run: |
        mamba env update --file environment-test.yml --name base
    - name: Install current project in dev mode
      run: |
        pip install -e .
    - name: Install pytest
      run: |
        mamba install -c conda-forge black pyflakes pytest
    - name: Test with pytest
      run: |
        pytest
    - name: Lint with pyflakes and black
      shell: bash
      run: |
        pyflakes jgo/*.py
        black --check .
